services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    networks:
      - aceup

  backend:
    build:
      context: ./backend
    working_dir: /rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ./backend:/rails
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=aceup_db
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - aceup

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=aceup_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aceup

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - aceup

volumes:
  db_data:

networks:
  aceup:
    driver: bridge
